### ISSUE TITLE
Add ability to select multiple photos at once

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#116]
When I add a photo to an observation from my photo library, I VERY MUCH want to be able to select more than one photo at a time. :-)

The option to import metadata should still exist, so I think the language should say:
"Import metadata?
Do you want to apply the date, time, and location from the first photo selected to this observation?"
Or something like that indicating that it uses data from the first photo when multiple are selected.

**Comment by kueda** [comment]
+1 from Durrell.

**Comment by alexshepard** [comment]
safe to fix this, Carrie?

**Comment by carrieseltzer** [comment]
Yes, thanks!

**Comment by ahrendsen** [comment]
~~Well, I for one think selecting multiple photos should be implemented. I was actually convinced that it just wasn't possible with the app and came here to submit a feature request that it should be worked in. I'm happy to see that there is an existing solution, but think there is a small segment of the population that would very much appreciate being able to select multiple photos through the app, rather than the sharing interface.~~

~~I also love that it's open source that I can have this experience. Thanks everyone for your hard work.~~

EDIT: Now I learn that you can do this after changing to "Advanced Mode". I guess I skipped the app tutorial when I was supposed to learn that I could turn that on! https://www.reddit.com/r/iNaturalist/comments/1mpjr7x/am_i_doing_something_wrong_with_multiple_photos/

Thinking about it more, I think that if you press the "Magic AI capture button" then decide to choose photos from the gallery, it should go to the "advanced mode gallery" so that multiple photos can be selected.
