### ISSUE TITLE
Explore Map: No Image Available when Zoomed In

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#151]
When zoomed all the way into the map, no image is available on the Explore map. Running version 8.1.3.

![img_0993](https://cloud.githubusercontent.com/assets/11527994/7149493/ecbd92fa-e2c2-11e4-88c2-2750cd3605fa.PNG)

**Comment by joellebel** [comment]
Just wanted to follow up on this... is there any way to limit the zoom level so we don't see the above screen. It's a bit jarring to the UX.

**Comment by alexshepard** [comment]
We can switch to using map (instead of satellite) tiles, which will fix this, since map tiles are vector images and thus zoom all the way in. I can also look into switching to Google Maps, which may or may not have this problem.

Apple doesn't notify us if a tile can't be loaded for a zoom level.

Last time I looked, different geographies had different levels of satellite fidelity for technical and political reasons. If we limit the app to not display over a certain zoom level, that could mean that in some areas we won't be showing some higher quality satellite photos that we could have shown. Even with a mostly reasonable threshold, users may still run into blank tiles if they zoom into an area with unusually low satellite fidelity.

**Comment by joellebel** [comment]
If we switch to using map (instead of satellite) tiles, can we still make satellite view available to users? It is definitely helpful at times. 

If Google Maps has a better map that would be great. However, if that's something big to implement, I don't see it as something we need to do in the immediate future. The current map is very functional.

**Comment by alexshepard** [comment]
We could make it so users could switch between map styles (satellite vs map) but then we'd still have the problem if the user has chosen satellite style and zoomed way in.

**Comment by joellebel** [comment]
That works for me. There are certainly times when I could use both. @kueda @loarie Any opinion?

**Comment by kueda** [comment]
Ok, sounds like the only actionable thing remaining here is to allow people to view map tiles, which requires design. I'm going to close b/c that seems like more of an issue for a larger design change to Explore.
