### ISSUE TITLE
build 129 not using location from photo metadata

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#154]
Adding a previously taken photo to an observation is not applying geolocation and is instead using current location. (iOS 8.1.2)

See here for same photo added under two different builds-- most recently added observation shows current user location by default.

http://www.inaturalist.org/observations/carrieseltzer?utf8=✓&q=&search_on=&quality_grade=any&geoprivacy=&identifications=any&captive=&place_id=&swlat=&swlng=&nelat=&nelng=&taxon_name=Viola&taxon_id=50829&day=&month=&year=&order_by=observations.id&order=desc&rank=&hrank=&lrank=&site=&tdate=&d1=&d2=&filters_open=true&view=table

Observation time is correctly recorded.

**Comment by alexshepard** [comment]
Currently, when you make an observation without a photo, we set the observation as "right here, right now."

Getting rid of that annoying "do you want to import the metadata from this photo" popup unfortunately means that if we already have an observation location & time, and the user adds another photo with conflicting information, we have to choose which to pick. Turns out that annoying popup solved a real problem. ;)

I'm open to suggestions about how to resolve this. Should new observations without photos default to unknown place & unknown time? Should I bring back the "do you want to import the metadata?" popup?

**Comment by carrieseltzer** [comment]
Sorry, I think I wasn't totally clear. I meant that starting a new observation and selecting from the camera roll brings up this issue, not just adding a photo to an observation that had none.

**Comment by naturalistcharlie** [comment]
IMHO, definitely don't make new observations without photos default to
unknown place... because I (and I think many others) do sometimes make
observations without photos. I actually think that annoying popup is a good
one, it isn't so bad and it's important for people to realize.  The other
options (using current location and not allowing import of geodata... or
automatically importing the location when someone might not intend to, for
instance if there was a GPS error) don't seem better. I think the most
important thing here is to make sure iNat still gets locationd ata for
photoless observations because there are lots of reasons one might want to
do this (hearing a bird, etc)

On Wed, Apr 15, 2015 at 3:38 PM, Alex Shepard <notifications@github.com>
wrote:

> Currently, when you make an observation without a photo, we set the
> observation as "right here, right now."
>
> Getting rid of that annoying "do you want to import the metadata from this
> photo" popup unfortunately means that if we already have an observation
> location & time, and the user adds another photo with conflicting
> information, we have to choose which to pick. Turns out that annoying popup
> solved a real problem. ;)
>
> I'm open to suggestions about how to resolve this. Should new observations
> without photos default to unknown place & unknown time? Should I bring back
> the "do you want to import the metadata?" popup?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/154#issuecomment-93542896>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by kueda** [comment]
I don't find that popup annoying. I generally want that choice, at least for the *first* photo I add from my library. Might be ok to omit it for subsequent ones, and that might be irrelevant now that you can select multiple photos. Sometimes I wish the app looked at the time stamp, and if the photo was only taken a few minutes prior to the observations created_at timestamp, just assume I'm still in the same spot, but then it might be a bit too magical.

**Comment by carrieseltzer** [comment]
I think there's two separate issues being discussed here:
1. Importing location metadata automatically when you select a photo from the camera roll at the time of creating a new observation (which isn't working now, but did work last week-- unless I'm totally misremembering).
2. Using a popup to ask about metadata use in cases other than a first photo in a new observation.

**Comment by alexshepard** [comment]
Yup, Carrie. 
Number 1 is easily fixable, working on repro/fix.

**Comment by alexshepard** [comment]
That first number 1 is better stated as:

When selecting from camera roll to create a new observation, location metadata comes from the user's current location, not the location of the selected photo(s).
