### ISSUE TITLE
Add designation for captive/cultivated

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#158]
Allow users the ability to designate an observation as captive/cultivated from within the app when adding or editing an observation.

Came up in comments on this observation: http://www.inaturalist.org/observations/1390998

I hadn't noticed the possibility didn't exist! Or if it does, it's hard to find!

**Comment by kueda** [comment]
Seconded. I can't tell if this is more a personal frustration or a serious problem with data quality, but it drives me nuts that people don't self-report this more often. Not sure if there's a good way to do this in mobile, though, or if that would even increase the amount of self-reported captive/cultivated status, since people don't seem to do it much on the web, either.

**Comment by carrieseltzer** [comment]
I think having the option in mobile would dramatically increase the self-reporting status as long as it's designed clearly. I wonder how many users ONLY use the app? Might be more than we think, especially among newbies. 



—

**Comment by naturalistcharlie** [comment]
Thirded. Usually it doesn't matter because I look at my observations on the
website right after uploading but during some times as right now when I am
traveling with patchy internet service I can't do that. Incidentally I
apologize flooding the site with "bird" and "plant" (including some non
wild ones) from Costa Rica but not surprisingly I don't have that much
internet access here.
