### ISSUE TITLE
Make links in comments clickable

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#218]
Feature request made in comments on this observation: http://www.inaturalist.org/observations/2102690

It doesn't appear possible to copy and paste the link either at least for version 2.6.2 build 234.

**Comment by loarie** [comment]
I also think its a priority to get clickable links definitely on the Observation Activity
![img_3375](https://cloud.githubusercontent.com/assets/598026/11154106/367710fc-89f2-11e5-92bf-7c4a2ef78e52.PNG)
lower priority on the Explore tab
![img_3374](https://cloud.githubusercontent.com/assets/598026/11154107/367af316-89f2-11e5-82fc-a9105d298118.PNG)
So that we 'welcomers' can reference getting started materials
![img_3376](https://cloud.githubusercontent.com/assets/598026/11154108/367b0d1a-89f2-11e5-86ba-7f26b8afe08e.PNG)

**Comment by alexshepard** [comment]
these UI elements aren't there anymore, and the replacements show HTML linked
