### ISSUE TITLE
we lost the "view on the web" link from the observation details

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/INaturalistIOS#247]
@kueda reports:
> We seem to have lost the ability to view the current obs on the website. This is pretty important to me to verify that upload really worked

I responded:
> If you share->copy, you're coping the iNat URL, which you can then paste into safari.

To which @kueda responded:
> also just frustrated by having even more taps to do one of the actions i do the most in the app

This last comment was vis-a-vis this issue, #245, and #246

**Comment by joellebel** [comment]
Sounds like we're not doing this for now because it could cause confusion for other users since the web browser app isn't quite responsive. 

@kueda If you really find you're needing it, I would put it as an option in the Share menu which pops up after tapping the Share icon in the upper right. Currently it's using platform share menu, so I'm assuming we'd have to do something custom.

**Comment by alexshepard** [comment]
Observation share now has an "Open in Safari" option.
