### ISSUE TITLE
Focus indicators for camera mode

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#260]
Filing this as an enhancement. It would be nice to have something similar if not the same focus indicators as the native camera app has. This helps the user better understand what they are focusing on and especially comes in handy when photographing bugs. 

I believe the native focus functionality also has a ui for brightness and darkness connected to the focus square. I don't think that is as important.

**Comment by naturalistcharlie** [comment]
would love this feature!

On Thu, Feb 11, 2016 at 1:47 PM, joellebel <notifications@github.com> wrote:

> Filing this as an enhancement. It would be nice to have something similar
> if not the same focus indicators as the native camera app has. This helps
> the user better understand what they are focusing on and especially comes
> in handy when photographing bugs.
>
> I believe the native focus functionality also a ui for brightness and
> darkness connected to the focus square. I don't think that is as important.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/260>.
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by alexshepard** [comment]
Because we have the custom overlay for the camera (to allow the photo library picker) we can't use the native focus square. So this would need to be built from scratch.

I think a better solution is to wait until we can support swift frameworks (after the restkit->realm transition is done), and then pick a third party camera/photo picker cocoapod. There are plenty of good open source options out there, no need to re-invent the wheel.

**Comment by joellebel** [comment]
Sounds good. Should we close this issue for now?

**Comment by alexshepard** [comment]
Hmm, I'll close it after I make an issue for picking a new third party camera framework.

**Comment by mixxster** [comment]
In addition to the focus box, focus lock, and exposure control would be very helpful.

Since iNaturalist relies almost entirely on photos to reach Research Grade for most observations, it would be very beneficial to improve the functionality of camera mode.

Can the camera mode be updated to include a focus box, focus lock, and exposure control? I wish the iNaturalist camera was more functional and behaved more like the default iOS camera, Camera+, or similar camera apps.

When photographing moving insects, species in tricky lighting, or tiny plant parts, all of these features can very important to getting a good shot. This is why I haven't been using the iNaturalist camera mode, but it would save me a lot of time if it were more capable.
