### ISSUE TITLE
Ob Detail Screen UX Refining

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#263]
Did a little tweaking for uniformity between tabs by adding and adjusting some vertical space for clarity...
# Punch Items
#### Proposed Design

![image](https://cloud.githubusercontent.com/assets/11527994/13412402/ea347ae4-def7-11e5-8889-3f08df4e51db.png)
#### Specs
- [ ] **Margin Fixing:** Make every margin 15pt where specified.
- [ ] **Tabs Background:** Change tabs background to white. 
- [ ] **Borders:** Add borders where specified if they're not already there
- [ ] **Location Label:** Change font color to #4A4A4A for better legibility

See below specs for reference...

![image](https://cloud.githubusercontent.com/assets/11527994/13412793/a60e5224-defa-11e5-9b4f-70c92671c348.png)

![image](https://cloud.githubusercontent.com/assets/11527994/13412818/d0ae395e-defa-11e5-933e-1b5eb365ae16.png)

![image](https://cloud.githubusercontent.com/assets/11527994/13412861/20bf1bd4-defb-11e5-9b98-da91e10ca425.png)

![image](https://cloud.githubusercontent.com/assets/11527994/13412868/2957688c-defb-11e5-8c31-24e547ff210e.png)
- [ ] **Comment and ID Buttons:** The buttons just need 6pt of padding above and below them to prevent mis-tapping

![image](https://cloud.githubusercontent.com/assets/11527994/13387766/e9394a36-de6e-11e5-92ba-954fb3109703.png)
- [ ] **Tabs Height:** Change tab height to 53pts high

![image](https://cloud.githubusercontent.com/assets/11527994/13412921/800dee26-defb-11e5-8441-94109ee49b59.png)
# Question

Does the location label text get smaller to accommodate the space? See below example...
![image](https://cloud.githubusercontent.com/assets/11527994/13387817/6af65f32-de6f-11e5-86bc-344fa686f6c8.png)

If so, can we keep it always the same size, but ellipsize it? We can always put the location name and lat/long on the location screen. (Which I think was specked out out for this screen, but I will make a separate issue for that.)

**Comment by joellebel** [comment]
Ok This puppy is ready to go!

**Comment by joellebel** [comment]
...and can we fix these margins too? 


![image](https://cloud.githubusercontent.com/assets/11527994/13413782/1d9e3ec4-df02-11e5-931d-be2e8384bbbf.png)



Gracias.

**Comment by alexshepard** [comment]
OK, looks good. 

You are correct, the text for the geocoded location does currently autoshrink. I'm happy to change it so that it doesn't, but here was my rational for making it autoshrink:

In some adhoc testing almost every geocoded location wouldn't totally fit on an iPhone 5s screen with a 17pt font. When its your own observation, this may not be as big of a deal, because you'll likely remember that `The Presidio of San Francisc...` probably means `The Presidio of San Francisco, San Francisco, CA, US`

However, when you're looking at someone else's observations, in say Observation of the Day, and `Monte Bello Open Space Preserve, Santa Clara County, US-CA, US` gets truncated to `Monte Bello Open Space Preser...` or `Raja Ampat, Irian Jaya Barat, Indonesia` gets truncated to `Raja Ampat, Irian Jaya Barat...` then unless you recognize the location name, you will need to tap through to the map and then zoom out just to learn what country the observation was made in.

Unfortunately, the most valuable information for a location _that you you're totally unfamiliar with_ is also the most likely to be truncated. I totally understand your desire for the text size to be consistent. I also want the information in an observation to be presented in a way that is easily and quickly understandable.

**Comment by joellebel** [comment]
@alexshepard I totally agree about seeing as much of the location text as possible. It was originally [specced at 15pt.] (https://cloud.githubusercontent.com/assets/11527994/11176926/804590b8-8bf6-11e5-848e-9e7e6459702e.JPG) However, why don't we try 14pt though and see how that looks across a variety of obs. 14pt might not be too small. 


FWIW It appears that 68% of folks reach an ob from the map view so they probably have an idea of location. 

![image](https://cloud.githubusercontent.com/assets/11527994/13645763/66c4978e-e5e1-11e5-9e53-07dfb57f8cac.png)

However, yes, this doesn't work for OOTD and in the future when you can reach an ob from someone's profile.

As far as putting the location and lat/long on the location screen, should I file an issue for that? It was in the original design, but I think we punted that down the road a bit in favor of getting the ob detail out.

**Comment by alexshepard** [comment]
> However, why don't we try 14pt and see how that looks across a variety of obs

OK

> It appears that 68% of folks reach an ob from the map view so they probably have an idea of location.

I think it's actually higher, 77%. But there are no maps on any of the project screens, so that will realistically drop down a bunch once we start using observation details in both locations.

> As far as putting the location and lat/long on the location screen, should I file an issue for that?

You already mentioned it in #237 but I haven't gotten to it yet.

**Comment by alexshepard** [comment]
@joellebel is there anything left to do in this issue?

**Comment by joellebel** [comment]
Need to double check something. Will get back to you.

**Comment by joellebel** [comment]
Ok. Would love to raise the tab icons 6pts. They've always been a little too low IMO. This will hopefully insure a nicely cushioned, tappable area. See below...

![image](https://cloud.githubusercontent.com/assets/11527994/26258389/67075ae8-3c79-11e7-8c0a-f266c18512dc.png)


Let me know how you would like to proceed. I can close this issue and make a new one if that's better. I realize this is a very old issue.

**Comment by alexshepard** [comment]
A new issue, and closing this one, would be great, thanks!
