### ISSUE TITLE
scientific name not showing in obs list when offline

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#269]
When you make an observation while offline and choose a taxon that has been cached locally and has a scientific name no common name, it shows up as "Unknown" in the observations list. Kind of annoying to test but this should work:
1. Observe http://www.inaturalist.org/taxa/60562-Gelae-donut on the website
2. Pull down your observations in the app. Don't tap on the obs you just made
3. Disconnect your phone from the Internet
4. Make a new obs in the app, and try to add the taxon Gelae donut. In the taxon chooser it should appear without a common name _and_ without an iconic taxon.
5. Look at your observation list. It should be listed as "Unknown.

**Comment by carrieseltzer** [comment]
I just had this happen to me but wasn't going to go through the trouble of
reporting it, but since you already did, I'll add to it a little. If you
type a description, it will display the description instead of "unknown".
The placeholder description continues to display for me in the "me" tab
even after it displays an image thumbnail for the taxon. I'm not sure yet
what will trigger it to display as an actual taxon name (maybe an id
agreement?).

**Comment by kueda** [comment]
Seems to be working as of build 425.
