### ISSUE TITLE
Returning Iconic Taxa Choices to Search UI

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#300]
We've decide to put back the iconic taxa list so it is visible when you first get to the search screen... the same way it used to be.

**Comment by alexshepard** [comment]
When did we decide this? We talked about it, but I don't remember a decision being made.l

**Comment by joellebel** [comment]
Oh. I misunderstood your request in this issue: [https://github.com/inaturalist/INaturalistIOS/issues/295] 

How does everyone feel about putting back the list of iconic taxa in the search ui of the current taxon chooser? It would work the same way the old one did in that when you arrive at the screen screen you'd see the list of iconic taxa under the search box.

**Comment by alexshepard** [comment]
When we talked about it in Slack, my concern was that switching to the new iconic-less taxa search  has produced on average the same number of identifications, but finer identifications (i.e. fewer Plants are more specific choices). Towards the end of that conversation I realized that I was using a national parks bioblitz week as a comparison point, so I would re-do the comparison with a different week.

I re-ran the numbers to compare the first week of April (with iconic taxa) with the first week of July (without iconic taxa). Here's what I found:
First week of April, average taxa changes per session: 0.275
First week of April, percentage of taxa chosen that were iconic: 12.7%

First week of July, average taxa changes per session: 0.29
First week of July, percentage of taxa chosen that were iconic: 8.3%

So I think my earlier analysis holds. Removing iconic taxa didn't reduce the number of times folks changed the taxa on observations, but it did result in fewer IDs to iconic taxa.

Based on that, I'm hesitant to return iconic taxa choices to the search UI since it seems like it's producing on average finer IDs, which seems like a good thing to me.

**Comment by alexshepard** [comment]
If people aren't sold on this analysis, let me know and I can calculate the average rank_level of IDs added by the iOS app using the taxon chooser over the past few months. This should more explicitly indicate whether there has been a change in the fineness/coarseness of IDs on average as a result of the removal of iconic taxa from the UI, and by how much.

**Comment by joellebel** [comment]
That sounds like it would be a helpful stat. These are interesting stats and if removing the iconic taxa from the flow results in finer IDs that is definitely a good thing. However, I'm not sure these stats tell us explicitly how well the user understands the flow and perhaps, taxonomy. 

Debating this may be taking up more of our time then working on the new taxon chooser which should hopefully be a lot more helpful to folks. I am happy to put it on the back burner for now. (Although, I'm curious to see a calculation of the average rank_level of IDs added by the iOS app using the taxon chooser over the past few months if it's something fairly easy to acquire.)

**Comment by alexshepard** [comment]
Ok, I'll add a todo for this week to try to calculate that based on exports from flurry.

**Comment by alexshepard** [comment]
can i close this in advance of a new taxon chooser @joellebel or do you still want this?

**Comment by joellebel** [comment]
Sure. We can close... but for the record I personally really miss the iconic taxa page :(
