### ISSUE TITLE
Progress bar needs numbers

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/INaturalistIOS#314]
@joellebel writes: 

> It would also be nice to have numbers next to the progress bar like "1/2" or "2/3" to indicate which photo is being uploaded. It's a little unconventional that a progress bar gets repeated (even though we're indicating the number of uploading objects in the header) If this is a big pain though, no biggie. Let me know and I can do a mock up.

**Comment by joellebel** [comment]
Ok. I'm assigning this issue to me and will make a mock up for it.

**Comment by joellebel** [comment]
Here's what I'm thinking....

The numbers indicate the number of progress bars that will be present.

![image](https://cloud.githubusercontent.com/assets/11527994/17410444/90c4c5d4-5a28-11e6-9fc7-ee573f83cf59.png)

**Comment by alexshepard** [comment]
If you look at https://github.com/yannickl/YLProgressBar you'll see some additional options for progress bar decoration that are built in to the progress bar that we're using. The percentage text in the demo there is customizable, so that text could say "2 of 4." Just another thought.

**Comment by alexshepard** [comment]
Also, the count on the observation row doesn't match the count in the header. Is that a cause for confusion?

**Comment by joellebel** [comment]
> Also, the count on the observation row doesn't match the count in the header. Is that a cause for confusion?

It might, but I think it's more confusing if there's double progress bars and no indication of why. We could put "2 photos of 3", but then I was thinking you'd have to make extra logic in there for syncing obs with no new photos. 

> If you look at https://github.com/yannickl/YLProgressBar you'll see some additional options for progress bar decoration that are built in to the progress bar that we're using. The percentage text in the demo there is customizable, so that text could say "2 of 4." Just another thought.

Just curious... Did something get left out of the above text? ...because the the mock up has "2 of 4" already in it.

**Comment by joellebel** [comment]
Looked at the  https://github.com/yannickl/YLProgressBar. I don't think we need to show percentage here of the active progress bar because we're already showing indicators in the header and perhaps below the progress bar. Good to know the options though.

**Comment by alexshepard** [comment]
The percentage text in the demo is customizable. It doesn't need to say the percentage, it could say "2 of 4." I offered it as an alternative to your mock up, in case you weren't aware that we could do it for free (UI-wise).

**Comment by joellebel** [comment]
Okeedoke. Here's a mock up of the alternative. Looking at it now I'm finding a little clunkier than the first solution. However, if it's lightning years easier to make, that's fine. It's also a little hard to read the text and using a gray bg and green indicator color would be more consistent with the app. Plus, I'm wondering if folks would be confused since the "2 of 4" is directly on the progress bar they may think it's referring to the state of the progress bar itself and not the amount of progress bars. 

@alexshepard what do you think? 

![image](https://cloud.githubusercontent.com/assets/11527994/17412085/c5f443fe-5a2f-11e6-8318-4091305e3b15.png)

**Comment by alexshepard** [comment]
![eb5c40ea92b5b583d67faa509bf8cd37ec3f28c27ec76c88dce201a087a267e4](https://cloud.githubusercontent.com/assets/515947/17412266/b8ea1f70-5a30-11e6-81e9-aaf76db7ace4.jpg)

**Comment by joellebel** [comment]
Ha. Ok. Original mock it is.

**Comment by alexshepard** [comment]
I think the direction we're going in the future is instead to make the progress bar somehow encompass all uploads for that observation, so if three photos need to be uploaded, then each would take up 1/3 of the progress bar.

**Comment by joellebel** [comment]
Ok. Is there a new issue for this? ...or it's just kinda understood that it's happening down the road?
