### ISSUE TITLE
new taxon details page

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/INaturalistIOS#377]

**Comment by joellebel** [comment]
# Screenshot of latest implementation

![image](https://cloud.githubusercontent.com/assets/11527994/26706208/6c814412-46f0-11e7-9e71-a1184a1d9ae3.png)

Just putting this here as a reminder for myself

**Comment by joellebel** [comment]
# Design Review

Just a few items that don't need to hold up a release:

- [ ]  **Divider Lines:** Can we add back the divider lines of 1pt #C8C7CC indicated where the arrows are. 

![image](https://cloud.githubusercontent.com/assets/11527994/26715150/634e171a-4729-11e7-9a9f-462b4242b940.png)

- [ ]  **Heading spacing:** Can we lower the h1 by like 2pts so it's clear the scientific name is referencing it. (Current is on the left, Design is on the right for comparison)

![image](https://cloud.githubusercontent.com/assets/11527994/26715190/91686a2e-4729-11e7-9de9-95f7559c9f78.png)



- [ ]  **Capitalization:** Is it any easy thing to use capitalization for the screen title? This would be a little more consistent with the Common name featured below the picture. See below...  (Current is on the left, Design is on the right for comparison)

And if possible to do this, can the screen title be capitalized on the map screen, as well?

![image](https://cloud.githubusercontent.com/assets/11527994/26715259/dd271f5a-4729-11e7-9e0a-5eecc27672e0.png)


- [ ] **Blurb Bottom Spacing:** The paragraph just needs a little more space below it. About 2-3pts or so. Feel free to eyeball it.  (Current is on the left, Design is on the right for comparison)



![image](https://cloud.githubusercontent.com/assets/11527994/26715537/ee387e32-472a-11e7-954b-d593234c5247.png)

- [ ] **Spacing Above and Below Button:** It would be great if the spacing above and below the button could be the same. See below...  (Current is on the left, Design is on the right for comparison)

![image](https://cloud.githubusercontent.com/assets/11527994/26715634/5a168446-472b-11e7-8cc2-2796a4804ff7.png)


- [ ] **Enlarged Photo CC:** I realize I didn't give you a design for this. Here it is...

![image](https://cloud.githubusercontent.com/assets/11527994/26716096/f25b62a2-472c-11e7-9bfb-c8921e8ec6db.png)

The bg of the band is white at 90%; The CC text is black, vertically middle-aligned within the band and center-aligned with the whole screen.

It would also be nice if the CC and it's background band didn't overlap the bottom controls area, but not a big deal, if it's a pain. 

![image](https://cloud.githubusercontent.com/assets/11527994/26716199/6119dad4-472d-11e7-8932-6075b49b23c0.png)







# Questions:

1. How does everyone feel about limiting the number of photos to 16 so we don't have all these dots. ...Or do you think folks would scroll through all 30, say if there were 30?

1. Since we're going with a non-cropped photo, most of the photos appear with a small amount space on the left and right and it kinda looks broken. (See below example) Is it possible to crop in horizontal photos so they take up the whole space, but not vertical photos? I'm assuming this is painful. 

![image](https://cloud.githubusercontent.com/assets/11527994/26716403/15ffdf0c-472e-11e7-87ee-4107d29ce45a.png)

**Comment by alexshepard** [comment]
Re: 1 , I'm fine with that
Re: 2, it's not realistically do-able

**Comment by alexshepard** [comment]
we don't have a lot of control over the design of the full screen photo screen, since that's provided by a third party framework.

if you want changes to that, probably best to open a new ticket, and i'll look into how customizable it is. ideally any changes to the full screen photo view would be used everywhere that we have full screen photos (like observation details and observation edit).

**Comment by joellebel** [comment]
@alexshepard this is looking great! 


One thing... I think the border is missing below the image and above the common name here...

![image](https://cloud.githubusercontent.com/assets/11527994/26749646/56732e40-47c4-11e7-8ba9-da33626ea26f.png)

**Comment by mixxster** [comment]
@joellebel @alexshepard
There is an older woman I work with who uses iNaturalist every day in the parks, she was upset with this change as it removed the link to Wikipedia and replaced it with the inaturalist.org page, which is not mobile friendly and not designed for the vision impaired. She says she now can no longer read more about the species because of her eyesight and small iPhone.

We request the link to the full Wikipedia article, or an easier to read article be brought back to the iNaturalist iOS app. In addition, there are many folks I work with who wish they could copy the name of the species to the clipboard, this cannot be done on the iNaturalist app, and it's frustrating.

**Comment by mixxster** [comment]
Can the (Source: Wikipedia) text be turned into a link to the full Wikipedia article?

**Comment by alexshepard** [comment]
Hi @mixxster if the iNaturalist taxa pages are not accessible, that’s something that should be resolved regardless.

We talked about making the (Source: Wikipedia) text a link, and it’s still something we’d like to do, but it didn’t make the cut for this release.

Pinch to zoom works on iOS in Safari, and there’s also the iOS zoom feature (in Settings->General->Accessibility) for the vision impaired, which could both help your friend navigate these iNaturalist taxa web pages. Are these not reasonable workarounds for her?

**Comment by mixxster** [comment]
I tried to walk her through it but she said she just wanted a link to the Wikipedia article. Perhaps the issue was actually caused by a change to iNaturalist.org, the taxon details page now defaults to the map view, and it used to default to the About view, with the article.

In any regard, this issue would be resolved by adding a link to a mobile-friendly Wikipedia article, and allowing the user to copy the name of the species to look up on their own.

**Comment by alexshepard** [comment]
The new taxon pages are done (since ~2.6.26), so I'm closing this out.
