### ISSUE TITLE
Enable / support copying text to clipboard.

### ISSUE THREAD

**Issue by mellis32** [inaturalist/INaturalistIOS#389]
There should be a way to copy text of a species name (especially scientific name) to the clipboard in iOS, this way we can look up more info about the species on the web, record in our field notes, or share the name/spelling of the species with others through communication.

Especially important to be able to copy the scientific name and possibly the common name. Having such a powerful identification tool but no means to copy simple text is frustrating.

I first mentioned this problem in my comment regarding the taxon details page #377.

**Edit:** See related issue, cannot paste in search box of the 'Explore' tab. See #411.

**Comment by alexshepard** [comment]
Thanks for the suggestion!

**Comment by mixxster** [comment]
Also I think it would be very important and helpful to support pasting text into the identification box.

Example: I could paste

**Comment by mixxster** [comment]
Also I think it would be very important and helpful to support pasting text into the identification box.

Example: I could paste "Asclepias amplexicaulis" rather than spending five minutes trying to spell it out while holding a bunch of gear in the field. This would be amazing if we could simply paste a species name. Thanks.

**Comment by alexshepard** [comment]
Hi @mixxster we already support pasting into the “Look up a species by name” text field.

**Comment by mixxster** [comment]
You're right about the field, thanks. I must have been doing something wrong in my attempt yesterday.

Would still be absolutely essential to copy text from the species suggestions list, and the species profile page. Especially the scientific name and possibly the common name.

I help run environmental programs in hundreds of parks and need quick ways to search for as much information as I can about species I encounter in the field. Having such a powerful identification tool but no means to copy simple text is frustrating.

**Comment by mixxster** [comment]
@alexshepard I figured out where paste wasn't working for me, I can't paste on the 'Explore' tab. I hope this can be fixed along with the copying problem.

**Comment by mellis32** [comment]
I'll donate $200 to Cal Academy / iNaturalist if this and #411 are fixed.

**Comment by mellis32** [comment]
@kueda @alexshepard I'll donate $200 to Cal Academy / iNaturalist if this and #411 are fixed.

To have such a powerful tool in the field that I isn't supporting basic copy and paste functionality really puts a damper on my field work and data collection productivity.

**Comment by alexshepard** [comment]
Hi @mellis32,

First of all, thanks for the offer, but we don't accept bounties.

Second of all, unfortunately you've caught the iOS team (me) at a difficult time. I'm working on a big re-write of a lot of the iNat iOS app. The app depends a lot on some really old third party software (an old version of restkit). This software isn't being actively developed or supported anymore and causes some real problems (we can't build cocoapods as frameworks with this version of restkit, so we can't mix swift into iNat, so can't use any newer third party libraries to add features is one big example). Working on this re-write to remove these old dependencies is my top priority, and it's taking a lot of time because this is the software at the base of all of iNat on iOS: all network api calls and all serialization of data happen via restkit.

So thanks for the bug reports, but please be patient. In the future, if you want to talk about how you're using iNat and your thoughts on future development of the app, your best bet would be to use the google group: http://groups.google.com/group/inaturalist/

Thanks again!

**Comment by alexshepard** [comment]
released in 2.7.6
