### ISSUE TITLE
Make Wikipedia snippet compliant with license requirements

### ISSUE THREAD

**Issue by dartar** [inaturalist/INaturalistIOS#504]
The current use of Wikipedia snippets in the iOS app (with a text-only: “Source: Wikipedia”) is not compliant with the attribution requirements of the CC BY SA license, which require content reusers to provide a backlink or some other form of attribution. See https://en.m.wikipedia.org/wiki/Wikipedia:Reusing_Wikipedia_content 

This, of course, unless the content is reused under fair use. Given how much iNat depends on community contributions and volunteer labor, proper attribution under the terms of the CC license would be more desirable.

**Comment by alexshepard** [comment]
Thanks @dartar will tackle this this week.

**Comment by kueda** [comment]
This seems like an issue that affects all uses of Wikipedia content across iNat, both due to non-compliant author attribution in situations where we can't use hyperlinks and the omission of the article title and license name/URI. I can see how we can deal with the article title and license name, but I don't see a way to retrieve the contributors to a particular page given the options at https://en.wikipedia.org/w/api.php. Can you provide some guidance here, @dartar? How can we use that API to get the information we'd need to provide attribution without links, i.e. with author names? 

Also, https://en.m.wikipedia.org/wiki/Wikipedia:Reusing_Wikipedia_content provides a good example of an ideal attribution with links, but not one without links. Can you provide such an example?

**Comment by dartar** [comment]
Attribution without links is usually the appropriate method for other media, like print or video. For an application or website, a link is generally considered sufficient for attribution (see option a. in the “Re-use of text under Creative Commons Attribution-ShareAlike” section of that page).

**Comment by alexshepard** [comment]
@dartar as Ken-ichi mentioned there are situations beyond the iNat iOS app where we cannot use hyperlinks. For example, iOS apps that target children are not allowed to link out of the app. In that case, our choices are: don't show wikipedia excerpts, or show an attribution without links. Is there official or unofficial wikipedia guidance on this case?

**Comment by alexshepard** [comment]
how's this? 

![Simulator Screen Shot - iPhone Xs - 2019-05-21 at 14 52 46](https://user-images.githubusercontent.com/515947/58133205-2ecf4a00-7bd8-11e9-990c-a6f10e95a13d.png)

**Comment by alexshepard** [comment]
Ken-ichi suggested the briefer: 

![Simulator Screen Shot - iPhone Xs - 2019-05-21 at 15 17 26](https://user-images.githubusercontent.com/515947/58134430-aa7ec600-7bdb-11e9-9b28-b159deff550b.png)

**Comment by dartar** [comment]
I hadn’t though if these restrictions on the ability to link out. Let me see if I can get additional guidance on this.

**Comment by dartar** [comment]
Looks great, guys 👌

**Comment by alexshepard** [comment]
thanks @dartar
