### ISSUE TITLE
IDs wrongly displayed as withdrawn

### ISSUE THREAD

**Issue by dartar** [inaturalist/INaturalistIOS#546]
I noticed multiple times on the app that some suggested IDs are marked as “withdrawn”. They are rendered correctly [on the web](https://www.inaturalist.org/observations/37044709) (see screenshots below) so this appears to be an iOS app bug. 

**App:**
![2EDCB197-5E16-4090-8325-DBC3470667C8](https://user-images.githubusercontent.com/209506/71951059-897cdc80-318e-11ea-81e6-33472c187c95.jpeg)

**Web:**
![F720BA3B-7F9C-483E-B359-67571CD5F7AB](https://user-images.githubusercontent.com/209506/71951060-897cdc80-318e-11ea-8931-ecd789538e54.jpeg)

**Comment by alexshepard** [comment]
Thanks for the bug report Dario. Unfortunately, I don't see this when I view this observation via Explore. Is there anything else you can do to help me reproduce? 

![Simulator Screen Shot - iPhone Xs - 2020-01-08 at 14 44 35](https://user-images.githubusercontent.com/515947/72022495-6f420d80-3225-11ea-96bb-5967421af512.png)

**Comment by alexshepard** [comment]
ah, nvm, was able to reproduce it on my device. seems to only occur when there's a withdrawn/superceded ID further up, that's scrolled off screen, which means it's got to do with cell reuse. apparently text cell attributes aren't always cleared, even if the text itself is. :/

should be fixed in the cb35f80, which will go out in 2.8.8 (not the release going out this weekend, but the next release).

thanks as always for reporting, @dartar
