### ISSUE TITLE
allow delete account

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/INaturalistIOS#567]

**Comment by alexshepard** [comment]
Do we need to copy android's login again flow or can we do what the web does?

**Comment by kueda** [comment]
The only difference on Android is that we require the user to enter their password before getting to the account deletion screen. I guess that's to prevent someone from grabbing your phone and deleting your account, but it still seems pretty extreme so I'd be ok with dropping that requirement. The deletion screen on Android and the web are almost identical from there.

**Comment by kueda** [comment]
FWIW, in order to `DELETE /users/:id.json`, you need to request an access token with the `account_delete` scope. The [equivalent Android issue](https://github.com/inaturalist/iNaturalistAndroid/issues/758#issuecomment-579044890) has some more details, and we can put together the equivalent curl commands if that helps.
